### PR TITLE
[xkeyboard-config] Map Xperia 10 III assistant button to camera. JB#60142

### PR DESCRIPTION
**Pull request by pvuorela**
Needs also https://github.com/mer-hybris/droid-hal-configs/pull/258

### CODE REVIEW

**Review by Thaodan — CHANGES_REQUESTED** [review]
Same here, the button is probably shared between different ports.

**Comment by pvuorela** [comment]
> Same here, the button is probably shared between different ports.

Yes, and that's ok. We have been just using one mapping to all the devices we've supported. Actually this being the jolla phone mapping here. In theory there could be a collision on the custom keycodes between devices, but in practice new ones are encountered only every few years. And if we'd have different keymaps, we'd need to get more support on configuring one for each device. 

With a high likelihood of never getting a collision we can just postpone these complication. Thus won't make changes here.

**Review by spiiroin — APPROVED** [review]
But neither the change + associated comment nor the git commit message exactly spells out what is happening / what these numbers are. But that might be just me being unfamiliar with the files in here.

I guess this is all right and turns assistant key to camera key in every device out there - which would be fine by me for now.

**Comment by pvuorela** [comment]
Added a few words to the commit message.

**Pull request merged**
